# Generated by Django 4.2.30 on 2026-06-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-идентификатор')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('death_date', models.DateField(verbose_name='Дата смерти')),
                ('portrait', models.ImageField(blank=True, upload_to='portraits/', verbose_name='Портрет')),
                ('remembering_title', models.CharField(blank=True, default='Помним', max_length=200, verbose_name='Заголовок «Помним…»')),
                ('remembering_text', models.TextField(blank=True, verbose_name='Развёрнутая биография')),
                ('events_intro', models.TextField(blank=True, default='Следующие мероприятия организованы для родных и друзей, чтобы вместе вспомнить и поддержать друг друга.', verbose_name='Вступление к событиям')),
                ('slideshow_music', models.FileField(blank=True, upload_to='music/', verbose_name='Музыка слайд-шоу')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница памяти',
                'verbose_name_plural': 'Страницы памяти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Текст воспоминания')),
                ('image', models.ImageField(blank=True, upload_to='tributes/', verbose_name='Фото')),
                ('video', models.FileField(blank=True, upload_to='tributes/videos/', verbose_name='Видео')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='memorials.memorial')),
            ],
            options={
                'verbose_name': 'Воспоминание',
                'verbose_name_plural': 'Воспоминания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='memorials.memorial')),
            ],
            options={
                'verbose_name': 'Событие таймлайна',
                'verbose_name_plural': 'Таймлайн',
                'ordering': ['order', 'year', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], default='photo', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Фото')),
                ('video', models.FileField(blank=True, upload_to='gallery/videos/', verbose_name='Видео')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='memorials.memorial')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('service', 'Служба'), ('reception', 'Поминки'), ('other', 'Другое')], default='service', max_length=20)),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('location_name', models.CharField(max_length=300, verbose_name='Место')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='memorials.memorial')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['order', 'date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BiographySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='biography/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biography_sections', to='memorials.memorial')),
            ],
            options={
                'verbose_name': 'Блок биографии',
                'verbose_name_plural': 'Блоки биографии',
                'ordering': ['order', 'id'],
            },
        ),
    ]
